[build]
  command = "npm run build:client"
  publish = "dist/spa"

[dev]
  command = "vite"
  port = 5173
  targetPort = 5173
  publish = "dist/spa"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "https://ai-legal-summarizer-assistant.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
